
spring:
  application:
    name: Gateway-Service
  cloud:
    gateway:
      routes:
        - id: Book-Service
          uri: ${BOOK_ROUTE_URI:http://localhost:8081/}
          predicates:
            - Path=/api/v1/book/**


        - id: Author-Service
          uri: ${AUTHOR_ROUTE_URI:http://localhost:8082/}
          predicates:
            - Path=/api/v1/author/**


        - id: Genre-Service
          uri: ${GENRE_ROUTE_URI:http://localhost:8083/}
          predicates:
            - Path=/api/v1/genre/**

    zipkin:
      base-url: http://localhost:9411
      sleuth:
        sampler:
          probability: 1.0



